### ISSUE TITLE
Information Architecture Update

### ISSUE THREAD

**Issue by derick-montague** [openbmc/webui-vue#56]
## Overview
IBM is integrating quite a bit of functionality into the Web UI. We are currently working on a card sort that we will be sharing and requesting feedback and collaboration on with the community.

Our goal is to provide an intuitive experience for all Web UI users regardless of platform. As this application grows, it will be critical that we have a robust information architecture. 

## Tasks

- [x] IBM feature inventory + OpenBMC mapping
- [x] Review existing & past IA research 
- [x] Send out survey to all Design Partners 
- [x] Create baseline IA, to be validated with Design Partners 
- [x] Conduct card sort with Design Partners to validate baseline IA 
- [x] Review findings with the community
- [x] Finalize and implement the updated IA

## Final Information Architecture
![image](https://user-images.githubusercontent.com/1183515/120001162-1cdbcb00-bf99-11eb-9703-f7ddf18ebfe4.png)

**Comment by derick-montague** [comment]
Verification of support for this at today's OpenBMC GUI Design Work Group.
