### ISSUE TITLE
# Server Control - IP KVM

### ISSUE THREAD

**Issue by derick-montague** [openbmc/webui-vue#6]
## Overview
Recreate page in Vue.js.

### Directive
- https://github.com/openbmc/phosphor-webui/blob/master/app/server-control/directives/kvm-console.js
- https://github.com/openbmc/phosphor-webui/blob/master/app/server-control/directives/kvm-console.html

### Controller(s)
- https://github.com/openbmc/phosphor-webui/blob/master/app/server-control/controllers/kvm-window-controller.js
- https://github.com/openbmc/phosphor-webui/blob/master/app/server-control/controllers/kvm-window-controller.html
- https://github.com/openbmc/phosphor-webui/blob/master/app/server-control/controllers/kvm-controller.html

## Tasks
- [x] Add route and all route meta data
- [x] Create page using page components
- [x] Determine if new components or layout required and verify with design
- [x] Include language translation

**Comment by lukkep** [comment]
We can help with that one. :)

**Comment by derick-montague** [comment]
I was able to assign it to @lukkep but still not Mateusz. :)

**Comment by matijas-1987** [comment]
It's interesting

**Comment by derick-montague** [comment]
@matijas-1987 do you want to be assigned to #7 also?

**Comment by Pavan-0** [comment]
Hi,

I came to know that phosphor-webui will be replaced by webui-vue.
We are using Openbmc version 2.7 and Windows OS for the Host.
I have two Queries regarding IP KVM.
1. Is there any way I can send CTRL+ALT+DEL command to the host from the KVM?
          Probably a menu button((Attached pic) on the KVM to send the command
2. Is developing keyboard mapping (attached pic Keyboard_mapping) for the KVM is in the road map
          This is to provide 1:1 mapping, character translation etc.
Please let me know if two features will be supported in IP KVM?

![Keyboard_mapping](https://user-images.githubusercontent.com/34479862/87654899-2a1f0b00-c775-11ea-9dc6-b1d150a29e1a.jpg)
![CTRL+ALT_DEL_KVM](https://user-images.githubusercontent.com/34479862/87654904-2be8ce80-c775-11ea-8b76-d2d2eedb071d.png)

Regards,
Pavan S

**Comment by matijas-1987** [comment]
Hi Pavan,

1. Yes, there will be a button to send CTRL+ALT+DEL
2. Can you explain keyboard mapping more? What is the difference between Map 1:1 and Auto?
I use the noVNC library, documentation- https://github.com/novnc/noVNC/blob/master/docs/API.md
If this option is available I could implement it, therefore, I need some examples to better understanding.

Regards,
Mateusz

**Comment by derick-montague** [comment]
The screen looks really good. I am going to merge https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34759.

I added this to the GUI Design Workgroup on Wednesday to review. There are some differences with the layouts between KVM and SoL. I think we should discuss these and determine how to make the experience more consistent. I have added a screen show below with the main differences between the two screens.

## KVM
![image](https://user-images.githubusercontent.com/1183515/88111587-d1d07a80-cb73-11ea-9f22-845b8b81267b.png)

## SoL
![image](https://user-images.githubusercontent.com/1183515/88111608-da28b580-cb73-11ea-9d24-a4b46f012c4b.png)

**Comment by matijas-1987** [comment]
I have added screens with KVM content (current height and SOL height)

**Current height**
<img width="731" alt="kvm-full" src="https://user-images.githubusercontent.com/66257423/88143784-1f8ec680-cbf8-11ea-8c63-7bbbc0185a47.png">

**SoL height**
<img width="734" alt="kvm-small-height" src="https://user-images.githubusercontent.com/66257423/88143794-23224d80-cbf8-11ea-98de-b8f6083d0396.png">

**Comment by lukkep** [comment]
Hello, 
Some suggestions regarding SoL/KVM comparison:

1. Naming should be standardized. 
    Left side menu contains names: **KVM** / **Serial over LAN console**
    I suggest changing names to **KVM console** / **SOL console**
(referring to [Wikipedia entry ](https://en.wikipedia.org/wiki/Serial_over_LAN) SOL should be all capital letters.

2. Below you can find my graphical mock with UI proposal. Few changes here:
- same naming convention,
- same windows sizes,
- buttons moved to right-top side,
- icon for shortcut (for KVM),
- icon for status (for KVM) - should apply proper icon for every status,
- "Status:" is bolded.

![KVM_SOL](https://user-images.githubusercontent.com/25308566/88160694-4efcfd80-cc0f-11ea-836b-5472b7a43809.jpg)

**Comment by Pavan-0** [comment]
Hi,

When we do a fresh install of OS, this is extremely hard because num lock
doesn’t work and numbers are very difficult to find.

When we need to set up a password, this is extremely complicated because
you don’t know where . or | or ! are. These kinds of characters are
necessary when you set a password. Hence we need to have keyboard mapping.


Auto : will automatically transfer the key sent to the language set on the
host OS.

1:1 mapping :  key is sent without any translation.

Translate: Option will enable users to select the language.


PFA for more details.


Let me know if we are supporting the above feature.


Regards,

Pavan S
