### ISSUE TITLE
Server Control - Virtual Media

### ISSUE THREAD

**Issue by derick-montague** [openbmc/webui-vue#7]
## Overview
Recreate page in Vue.js

### Controllers
- https://github.com/openbmc/phosphor-webui/blob/master/app/server-control/controllers/virtual-media-controller.js

## Tasks
- [ ] Add route and all route meta data
- [ ] Create page using page components
- [ ] Determine if new components or layout required and verify with design
- [ ] Include language translation

**Comment by erasad22** [comment]
Mock created for Control -> Virtual Media.

![image](https://user-images.githubusercontent.com/15446786/86573373-da199a80-bf63-11ea-9cd8-fad31e56ebdd.png)

**Comment by derick-montague** [comment]
Thank you, @erasad22 for working on this. I have added this to the GUI Design Workgroup conversation for today.

**Comment by derick-montague** [comment]
@matijas-1885 - you want to work on this one also?

**Comment by derick-montague** [comment]
@matijas-1987

**Comment by matijas-1987** [comment]
@derick-montague this issue will be made by Asad but you can assign to me.

**Comment by matijas-1987** [comment]
**Mock-up:**

![vm](https://user-images.githubusercontent.com/66257423/88158696-a51c7180-cc0c-11ea-989f-8623a6b60c75.jpg)

**Comment by chineweff** [comment]
I got errors when using virtual media.
![a](https://user-images.githubusercontent.com/22802902/89382800-f872e180-d72d-11ea-9c28-8e91cb652821.png)

This error messages were from
https://github.com/openbmc/phosphor-webui/blob/master/app/server-control/controllers/virtual-media-controller.js

Does anyone have any ideas?

**Comment by derick-montague** [comment]
> I got errors when using virtual media.

It looks like you opened an issue in the correct repository already, https://github.com/openbmc/phosphor-webui/issues/116. This feature has not been developed in the new UI framework.

**Comment by derick-montague** [comment]
Gerrit review: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35396
